/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Lab11 */

#ifndef _Included_Lab11
#define _Included_Lab11
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Lab11
 * Method:    sort01
 * Signature: ([Ljava/lang/Double;Ljava/lang/Boolean;)[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_Lab11_sort01
  (JNIEnv *, jobject, jobjectArray, jobject);

/*
 * Class:     Lab11
 * Method:    sort02
 * Signature: ([Ljava/lang/Double;)[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_Lab11_sort02
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     Lab11
 * Method:    sort03
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Lab11_sort03
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
